# Run:
# ```bash
# dart run build_runner build
# ```
# to update models

name: example
description: Example for data_classes package.
version: 1.12.0
homepage: https://github.com/priezz/data_classes
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  data_classes:
    git: https://github.com/priezz/data_classes.git

dev_dependencies:
  build_runner: ^2.3.3
# dependency_overrides:
#   data_classes:
#     path: ../
