# Run:
# ```bash
# pub run build_runner build
# ```
# to update models

name: example
description: Automatically generates immutable data classes for you based on a mutable "blueprint" class.
version: 1.0.1
author: Marcel Garus <marcel.garus@gmail.com>
homepage: https://github.com/marcelgarus/flutter_data_classes

dependencies:
  data_classes:
    git:
      url: https://github.com/priezz/data_classes.git
      path: data_classes

dev_dependencies:
  build_runner: ^1.10.0
  data_classes_generator:
    git:
      url: https://github.com/priezz/data_classes.git
      path: data_classes_generator

dependency_overrides:
  # analyzer: ^0.38.5
  data_classes:
    path: ../data_classes/
  data_classes_generator:
    path: ../data_classes_generator/
