builders:
  data_classes:
    applies_builders: ["source_gen|combining_builder"]
    auto_apply: dependents
    build_extensions: { ".dart": [".data_class.g.part"] }
    build_to: cache
    builder_factories: ["generateDataClass"]
    defaults:
      generate_for: [ "lib/**.dart", "test/**.dart" ]
    import: "package:data_classes_generator/data_classes_generator.dart"
    target: ":data_classes_generator"
