name: data_classes_generator
description: Automatically generates data classes for you based on a "blueprint" class.
version: 1.7.0
homepage: https://github.com/priezz/data_classes

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.1.0
  build: ^2.0.0
  # build:
  #   git:
  #     url: https://github.com/dart-lang/build.git
  #     path: build
  # collection: ^1.15.0
  data_classes:
    git:
      url: https://github.com/priezz/data_classes.git
      path: data_classes
  source_gen: ^0.9.10+4

dev_dependencies:
  build_runner: ^1.12.0

dependency_overrides:
  build:
    git:
      url: git://github.com/dart-lang/build.git
      path: build
  build_config:
    git:
      url: git://github.com/dart-lang/build.git
      path: build_config
  build_resolvers:
    git:
      url: git://github.com/dart-lang/build.git
      path: build_resolvers
  build_runner:
    git:
      url: https://github.com/dart-lang/build.git
      path: build_runner
  build_runner_core:
    git:
      url: https://github.com/dart-lang/build.git
      path: build_runner_core
  data_classes:
    path: ../data_classes/
  http_multi_server: ^3.0.0
  source_gen:
    git:
      url: https://github.com/dart-lang/source_gen.git
      path: source_gen
  timing: ^1.0.0
