name: data_classes_generator
description: Automatically generates data classes for you based on a "blueprint" class.
version: 1.8.0
homepage: https://github.com/priezz/data_classes

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  analyzer: ^2.8.0
  build: ^2.1.1
  data_classes:
    git:
      url: https://github.com/priezz/data_classes.git
      path: data_classes
  dartx: ^1.0.0
  source_gen: ^1.2.0

dev_dependencies:
  build_runner: ^2.1.5
# dependency_overrides:
#   data_classes:
#     path: ../data_classes/
