name: data_classes_generator
description: Automatically generates immutable data classes for you based on a mutable "blueprint" class.
version: 3.0.0
author: Marcel Garus <marcel.garus@gmail.com>
homepage: https://github.com/marcelgarus/data_classes

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ">=0.39.0 <1.0.0"
  build: ">=0.12.0 <2.0.0"
  # data_classes: ^3.0.0
  # data_classes:
  #   path: ../data_classes/
  data_classes:
    git:
      url: https://github.com/priezz/data_classes.git
      path: data_classes
  source_gen: ^0.9.4+6

dev_dependencies:
  build_runner: ^1.7.2
