name: data_classes_generator
description: Automatically generates data classes for you based on a "blueprint" class.
version: 1.7.0
homepage: https://github.com/priezz/data_classes

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.7.1
  build: ^2.0.2
  data_classes:
    git:
      url: https://github.com/priezz/data_classes.git
      ref: null_safety
      path: data_classes
  dartx: ^0.7.1
  source_gen: ^1.0.1

dev_dependencies:
  build_runner: ^2.0.4

# dependency_overrides:
#   data_classes:
#     path: ../data_classes/
