name: data_classes_generator
description: Automatically generates data classes for you based on a "blueprint" class.
version: 1.4.1
homepage: https://github.com/priezz/data_classes

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  analyzer: ^0.40.6
  build: ^1.6.1
  data_classes:
    # path: ../data_classes/
    git:
      url: https://github.com/priezz/data_classes.git
      path: data_classes
  source_gen: ^0.9.10+1

dev_dependencies:
  build_runner: ^1.10.13
