builders:
  generators:
    applies_builders: ["source_gen|combining_builder"]
    auto_apply: dependents
    build_extensions: { ".dart": [".sugar.g.part"] }
    build_to: cache
    builder_factories: ["generateSugarClasses"]
    defaults:
      generate_for: [ "lib/**.dart", "test/**.dart" ]
    import: "package:data_classes/generators.dart"
    target: ":data_classes"
