name: data_classes
description: Automatically generates data classes for you based on a "blueprint" class.
version: 1.7.1
homepage: https://github.com/priezz/data_classes

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  dartx: ^0.7.1

dependency_overrides:
  checked_yaml: ^2.0.1
  pubspec_parse: ^1.0.0
