name: data_classes
description: Automatically generates data classes for you based on a "blueprint" class.
version: 1.3.0
homepage: https://github.com/priezz/data_classes

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  collection: ^1.14.13
  json_serializable: ^3.4.1
  meta: ^1.1.8
