name: data_classes
description: Automatically generates data classes for you based on a "blueprint" class.
version: 4.0.0
author: Alexandr Priezzhev <a@priezz.net>, Marcel Garus <marcel.garus@gmail.com>
homepage: https://github.com/priezz/data_classes

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  collection: ">=1.14.11"
  json_serializable: ">=3.2.3"
  meta: ^1.1.8
